#pragma once

#include <variant_RAK3172_MODULE.h>

//#define FORMAT_FS
//#define LORAWAN_RFSWITCH_PINS PA8, PC13

#define LFS_BLOCK_SIZE (4096)

#define LORAWAN_RFSWITCH_PINS           PB8, PC13
#define LORAWAN_RFSWITCH_PIN_COUNT      2
#define LORAWAN_RFSWITCH_OFF_VALUES     LOW, LOW
#define LORAWAN_RFSWITCH_RX_VALUES      HIGH, LOW
#define LORAWAN_RFSWITCH_RFO_LP_VALUES  LOW, HIGH
#define LORAWAN_RFSWITCH_RFO_HP_VALUES  LOW, HIGH

#undef RNG
